#!/usr/bin/env python3
"""Emit a kernel-checked Lean 4 proof that a 3x3 matrix-multiplication scheme is correct.

Input: a hill-format solution.json with fields u, v, w (rows of 9 coefficients, each an
integer or [numerator, denominator]).

Index convention (copied from the hill's eval.py `_target`/`_check_brent`):
  A is row-major: a = 3*row + inner
  B is row-major: b = 3*inner + column
  C is column-major: c = 3*column + row
  target(a, b, c) = 1 iff inner(a) == inner(b) and c == 3*column(b) + row(a), else 0.
Brent identity (a, b, c): sum_t u[t][a] * v[t][b] * w[t][c] = target(a, b, c).

Fractional coefficients are handled by clearing denominators per factor:
  Du = lcm of all u denominators (likewise Dv, Dw), U = Du*u, V = Dv*v, W = Dw*w (all integers).
  The rational identity holds iff sum_t U[t][a] V[t][b] W[t][c] = Du*Dv*Dw * target(a,b,c),
  because Du*Dv*Dw > 0. The Lean file states that integer form.

Usage:
  python3 gen_brent.py solution.json -o Brent.lean [--name Laderman]
      [--mode single|split] [--tactic decide|kernel]

  --mode single  one proposition `forall a b c : Fin 9, ...` proved by one decide (default)
  --mode split   729 separate lemmas plus a combining theorem (fallback if single is slow)
  --tactic decide  plain `decide` (elaborator evaluates the Decidable instance, kernel re-checks)
  --tactic kernel  `decide +kernel` (skips elaborator evaluation, kernel only; default)
Neither mode ever uses native_decide, so no `Lean.ofReduceBool` axiom is introduced.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from fractions import Fraction
from pathlib import Path

MAX_RANK = 40
MAX_MAGNITUDE = 1_000_000


def coefficient(value, label: str) -> Fraction:
    # Mirrors the hill's _coefficient validation.
    if type(value) is int:
        num, den = value, 1
    elif isinstance(value, list) and len(value) == 2 and all(type(x) is int for x in value):
        num, den = value
    else:
        raise ValueError(f"{label} must be an integer or [numerator, denominator]")
    if den < 1 or abs(num) > MAX_MAGNITUDE or den > MAX_MAGNITUDE:
        raise ValueError(f"{label} is outside the coefficient bounds")
    return Fraction(num, den)


def factor(data, name: str):
    if not isinstance(data, list) or not 1 <= len(data) <= MAX_RANK:
        raise ValueError(f"{name} must contain between 1 and {MAX_RANK} rows")
    rows = []
    for r, row in enumerate(data):
        if not isinstance(row, list) or len(row) != 9:
            raise ValueError(f"{name}[{r}] must have exactly 9 coefficients")
        rows.append([coefficient(x, f"{name}[{r}][{i}]") for i, x in enumerate(row)])
    return rows


def target(a: int, b: int, c: int) -> int:
    row, inner = divmod(a, 3)
    b_inner, column = divmod(b, 3)
    return int(inner == b_inner and c == 3 * column + row)


def clear(rows):
    d = 1
    for row in rows:
        for x in row:
            d = math.lcm(d, x.denominator)
    return d, [[int(x * d) for x in row] for row in rows]


def python_check(U, V, W, D):
    """Pre-flight in Python so an invalid scheme fails fast with a readable message."""
    bad = []
    for a in range(9):
        for b in range(9):
            for c in range(9):
                s = sum(U[t][a] * V[t][b] * W[t][c] for t in range(len(U)))
                if s != D * target(a, b, c):
                    bad.append((a, b, c, s, D * target(a, b, c)))
    return bad


def lean_rows(rows) -> str:
    return "[\n" + ",\n".join("  [" + ", ".join(str(x) for x in row) + "]" for row in rows) + "\n]"


def emit(U, V, W, D, dens, name: str, mode: str, tactic: str, source: str) -> str:
    tac = "decide +kernel" if tactic == "kernel" else "decide"
    rank = len(U)
    support = sum(1 for M in (U, V, W) for row in M for x in row if x != 0)
    out = []
    out.append(f"""/-!
# Brent-identity certificate: {name}

Generated by gen_brent.py from `{Path(source).name}`.
rank = {rank}, support = {support}, denominators cleared: Du = {dens[0]}, Dv = {dens[1]}, Dw = {dens[2]}.

Convention (hill eval.py): A row-major (a = 3*row + inner), B row-major (b = 3*inner + col),
C column-major (c = 3*col + row). Each term t computes (sum_i U[t][i] A[i]) * (sum_j V[t][j] B[j])
and contributes W[t][c] times that product to output coordinate c.

The 729 Brent identities, after scaling u, v, w by Du, Dv, Dw, read
  sum_t U[t][a] * V[t][b] * W[t][c] = D * target(a, b, c),   D = Du*Dv*Dw = {D}.
Proved in core Lean 4 by kernel evaluation; native_decide is not used.
-/

namespace Brent.{name}

def U : List (List Int) := {lean_rows(U)}

def V : List (List Int) := {lean_rows(V)}

def W : List (List Int) := {lean_rows(W)}

/-- Common scale factor Du*Dv*Dw (1 for an integer scheme). -/
def D : Int := {D}

/-- Tensor of 3x3 matrix multiplication in the hill's index convention. -/
def target (a b c : Nat) : Int :=
  if a % 3 = b / 3 ∧ c = 3 * (b % 3) + a / 3 then 1 else 0

/-- Coefficient of A[a] B[b] C[c] in the scheme: sum over terms of U[t][a] * V[t][b] * W[t][c]. -/
def brentSum (a b c : Nat) : Int :=
  (U.zip (V.zip W)).foldl
    (fun acc r => acc + r.1.getD a 0 * r.2.1.getD b 0 * r.2.2.getD c 0) 0

theorem rank_eq : U.length = {rank} ∧ V.length = {rank} ∧ W.length = {rank} := by decide
""")
    if mode == "single":
        out.append(f"""
/-- All 729 Brent identities, as one decidable proposition. -/
theorem brent_identities :
    ∀ a : Fin 9, ∀ b : Fin 9, ∀ c : Fin 9,
      brentSum a.val b.val c.val = D * target a.val b.val c.val := by
  {tac}
""")
    else:
        for a in range(9):
            for b in range(9):
                for c in range(9):
                    out.append(
                        f"theorem b_{a}_{b}_{c} : brentSum {a} {b} {c} = D * target {a} {b} {c} := by {tac}\n"
                    )
        # Assemble hierarchically (9-way matches) so no single match has 729 arms.
        stmt = "brentSum a.val b.val c.val = D * target a.val b.val c.val"
        for a in range(9):
            for b in range(9):
                arms = "\n".join(f"  | ⟨{c}, _⟩ => b_{a}_{b}_{c}" for c in range(9))
                out.append(f"theorem r_{a}_{b} : ∀ c : Fin 9, brentSum {a} {b} c.val = D * target {a} {b} c.val\n{arms}\n")
        for a in range(9):
            arms = "\n".join(f"  | ⟨{b}, _⟩ => r_{a}_{b}" for b in range(9))
            out.append(f"theorem s_{a} : ∀ b : Fin 9, ∀ c : Fin 9, brentSum {a} b.val c.val = D * target {a} b.val c.val\n{arms}\n")
        arms = "\n".join(f"  | ⟨{a}, _⟩ => s_{a}" for a in range(9))
        out.append(f"""
/-- All 729 Brent identities, assembled from the per-index lemmas. -/
theorem brent_identities :
    ∀ a : Fin 9, ∀ b : Fin 9, ∀ c : Fin 9, {stmt}
{arms}
""")
    out.append(f"""
end Brent.{name}

#print axioms Brent.{name}.rank_eq
#print axioms Brent.{name}.brent_identities
""")
    return "".join(out)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("solution")
    p.add_argument("-o", "--output", default="Brent.lean")
    p.add_argument("--name", default="Scheme")
    p.add_argument("--mode", choices=["single", "split"], default="single")
    p.add_argument("--tactic", choices=["decide", "kernel"], default="kernel")
    p.add_argument("--no-precheck", action="store_true",
                   help="skip the Python pre-check (for testing that Lean itself rejects a bad scheme)")
    args = p.parse_args()

    if not args.name.isidentifier():
        print(f"error: --name must be a Lean-safe identifier, got {args.name!r}", file=sys.stderr)
        return 2
    data = json.loads(Path(args.solution).read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict) or set(data) != {"u", "v", "w"}:
        print('error: solution.json must contain only "u", "v", and "w"', file=sys.stderr)
        return 2
    try:
        u, v, w = factor(data["u"], "u"), factor(data["v"], "v"), factor(data["w"], "w")
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    if not len(u) == len(v) == len(w):
        print("error: u, v, w must have the same row count", file=sys.stderr)
        return 2
    (du, U), (dv, V), (dw, W) = clear(u), clear(v), clear(w)
    D = du * dv * dw
    bad = [] if args.no_precheck else python_check(U, V, W, D)
    if bad:
        a, b, c, got, want = bad[0]
        print(
            f"error: scheme is NOT a valid 3x3 matmul decomposition ({len(bad)} of 729 identities fail); "
            f"first failure A[{a}] B[{b}] C[{c}]: scaled sum {got}, expected {want}. No Lean file written.",
            file=sys.stderr,
        )
        return 1
    text = emit(U, V, W, D, (du, dv, dw), args.name, args.mode, args.tactic, args.solution)
    Path(args.output).write_text(text, encoding="utf-8")
    print(f"wrote {args.output}: rank {len(U)}, D = {D}, mode {args.mode}, tactic {args.tactic}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
