/-!
# Brent-identity certificate: scheme139

Generated by gen_brent.py from `best139.json`.
rank = 23, support = 139, denominators cleared: Du = 1, Dv = 1, Dw = 1.

Convention (hill eval.py): A row-major (a = 3*row + inner), B row-major (b = 3*inner + col),
C column-major (c = 3*col + row). Each term t computes (sum_i U[t][i] A[i]) * (sum_j V[t][j] B[j])
and contributes W[t][c] times that product to output coordinate c.

The 729 Brent identities, after scaling u, v, w by Du, Dv, Dw, read
  sum_t U[t][a] * V[t][b] * W[t][c] = D * target(a, b, c),   D = Du*Dv*Dw = 1.
Proved in core Lean 4 by kernel evaluation; native_decide is not used.
-/

namespace Brent.scheme139

def U : List (List Int) := [
  [0, 0, 0, 1, -1, -1, 0, 0, 0],
  [0, 0, 0, 0, -1, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0, -1, 0, 0],
  [0, -1, 0, 0, 0, 0, 0, 0, 0],
  [1, 0, 0, -1, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, -1, 0, 0, 0],
  [0, -1, 0, 0, 0, 0, -1, 1, 0],
  [0, -1, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, 0, 0, 1, 0, 0, -1, 1],
  [-1, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, 0, 0, -1, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0, 0, -1, 0],
  [0, 0, -1, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, -1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, -1, 0, 1, 1, 0, 0],
  [0, 0, 1, 0, 0, -1, 0, 0, 0],
  [0, 0, 0, -1, 0, 1, 1, 0, -1],
  [0, 0, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 1, 0, 0, -1, 0, 0],
  [-1, -1, 1, 0, 0, 0, 0, 0, 0],
  [1, 0, 0, 0, 0, -1, 0, 0, 0]
]

def V : List (List Int) := [
  [0, 0, -1, 0, 0, 0, 0, 0, 0],
  [1, 0, 0, 1, 0, 0, 0, 0, 0],
  [1, 0, 0, 1, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, -1, 0, 0],
  [-1, 0, -1, 0, 0, 0, 0, 0, 0],
  [0, 0, -1, 0, 0, 0, 0, 0, -1],
  [0, 0, 0, 1, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, -1, 0, 1, 0, 0],
  [0, 0, 0, 0, 1, 0, 0, 0, 0],
  [0, -1, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 1, 0, 0, 1, 0],
  [0, 0, 1, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, -1, -1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 1, 0],
  [1, 0, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 1, 0, 0, 1, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 1, 1],
  [0, 0, 0, 0, 0, 0, 1, 0, 1],
  [0, 0, 0, 0, 0, 0, 0, 1, 1],
  [1, 1, 0, 1, 1, 0, 0, 0, 0],
  [0, 1, 1, 0, 0, 0, 0, 1, 1],
  [0, 0, 0, 0, 0, 0, -1, 0, 0],
  [0, 0, 1, 0, 0, 0, -1, 0, 0]
]

def W : List (List Int) := [
  [0, 1, 0, 0, 0, 0, 0, -1, -1],
  [0, -1, -1, 0, 1, 1, 0, 0, 0],
  [0, 0, -1, 0, 1, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, -1, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, -1, 0, 1, 1, 0],
  [0, 0, 1, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 1, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, -1, 0, 0, 1],
  [0, 0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 1, 0, 0, -1],
  [0, 0, 0, 0, 0, 0, 0, -1, -1],
  [0, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, 0, -1, 0, 0, 0, 0, 0],
  [1, 1, 0, 0, 0, 0, 0, 0, 0],
  [-1, 0, -1, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0, 0, 0, 1],
  [0, 0, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, -1],
  [0, 0, 0, 0, 1, 1, 0, 0, 0],
  [0, 0, 0, 0, 1, 0, 0, 0, 0],
  [-1, 0, 0, 1, 0, 0, 1, 0, 0],
  [0, 1, 0, 0, 0, 0, 1, 0, 0]
]

/-- Common scale factor Du*Dv*Dw (1 for an integer scheme). -/
def D : Int := 1

/-- Tensor of 3x3 matrix multiplication in the hill's index convention. -/
def target (a b c : Nat) : Int :=
  if a % 3 = b / 3 ∧ c = 3 * (b % 3) + a / 3 then 1 else 0

/-- Coefficient of A[a] B[b] C[c] in the scheme: sum over terms of U[t][a] * V[t][b] * W[t][c]. -/
def brentSum (a b c : Nat) : Int :=
  (U.zip (V.zip W)).foldl
    (fun acc r => acc + r.1.getD a 0 * r.2.1.getD b 0 * r.2.2.getD c 0) 0

theorem rank_eq : U.length = 23 ∧ V.length = 23 ∧ W.length = 23 := by decide

/-- All 729 Brent identities, as one decidable proposition. -/
theorem brent_identities :
    ∀ a : Fin 9, ∀ b : Fin 9, ∀ c : Fin 9,
      brentSum a.val b.val c.val = D * target a.val b.val c.val := by
  decide +kernel

end Brent.scheme139

#print axioms Brent.scheme139.rank_eq
#print axioms Brent.scheme139.brent_identities
